name: AI Security Check for Pull Requests

on:
  pull_request:
    branches:
      - main

jobs:
  ai_security_check_for_pull_requests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Analyze code
        id: ai_security_check
        run: |
          echo "PR_COMMENT_BASE64=$(node ./ai-security-check-for-pr.js)" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_REPOSITORY: ${{ github.repository }}
          GH_EVENT_PULL_REQUEST_NUMBER: ${{ github.event.number }}
          OPENAI_TOKEN: ${{ secrets.OPENAI_TOKEN }}

      - name: Comment on pull request
        uses: actions/github-script@v6
        env:
          PR_COMMENT_BASE64: ${{ steps.ai_security_check.outputs.PR_COMMENT_BASE64 }}
        with:
          github-token: ${{ secrets.GH_TOKEN }}
          script: |
            const prCommentBase64 = process.env.PR_COMMENT_BASE64 || "";
            const prComment = Buffer.from(prCommentBase64, "base64").toString("utf8") || "No security or privacy issues found.";
            const { data } = await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: prComment
            });
